project:
  type: website

website:
  title: "Drew Shives"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - gallery.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

