project:
  type: website
  output-dir: docs

website:
  title: "Drew Shives"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - href: "https://www.kimjunghaphoto.me"
        text: KJH Photo
      - presentations.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

